name: Rename the project from template

on: [push]

permissions: write-all

jobs:
  rename-project:
    if: ${{ !contains (github.repository, '/nextjs-typescript-mui-redux-toolkit-template') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # by default, it uses a depth of 1
          # this fetches all history so that we can read each commit
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}' | tr '-' '_' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        shell: bash

      - run: echo "REPOSITORY_URLNAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash

      - run: echo "REPOSITORY_OWNER=$(echo '${{ github.repository }}' | awk -F '/' '{print $1}')" >> $GITHUB_ENV
        shell: bash

      - name: Fetch repository information
        id: fetch_repo_info
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPO_OWNER=${{ env.REPOSITORY_OWNER }}
          REPO_NAME=${{ env.REPOSITORY_URLNAME }}
          REPO_INFO=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/$REPO_OWNER/$REPO_NAME)
          EMAIL=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/users/$REPO_OWNER | jq -r .email)
          DESCRIPTION=$(echo "$REPO_INFO" | jq -r .description)
          echo "REPOSITORY_OWNER_EMAIL=${EMAIL}" >> $GITHUB_ENV
          echo "REPOSITORY_DESCRIPTION=${DESCRIPTION}" >> $GITHUB_ENV
        shell: bash

      - name: Is this still a template
        id: is_template
        run: echo "::set-output name=is_template::$(ls .github/template.yml &> /dev/null && echo true || echo false)"

      - name: Make rename_project.sh executable
        run: chmod +x .github/rename_project.sh

      - name: Rename the project
        if: steps.is_template.outputs.is_template == 'true'
        run: |
            echo "Renaming the project with -a(author) ${{ env.REPOSITORY_OWNER }} -e(email) ${{ env.REPOSITORY_OWNER_EMAIL }} -n(name) ${{ env.REPOSITORY_NAME }} -u(urlname) ${{ env.REPOSITORY_URLNAME }} -d(description) ${{ env.REPOSITORY_DESCRIPTION }}"
            .github/rename_project.sh -a ${{ env.REPOSITORY_OWNER }} -e ${{ env.REPOSITORY_OWNER_EMAIL }} -n ${{ env.REPOSITORY_NAME }} -u ${{ env.REPOSITORY_URLNAME }} -d "${{ env.REPOSITORY_DESCRIPTION }}"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "✅ Ready to clone and code."
          # commit_options: '--amend --no-edit'
          push_options: --force
